CREATE DATABASE IF NOT EXISTS timesheetdatabase; 
USE timesheetdatabase;


-- Drop tables if they exist
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS timesheet;
DROP TABLE IF EXISTS payroll;
DROP TABLE IF EXISTS salary;



CREATE TABLE users (
		id INT AUTO_INCREMENT PRIMARY KEY,
		username VARCHAR(50) NOT NULL UNIQUE,
		password VARCHAR(255) NOT NULL,
		email VARCHAR(100) NOT NULL UNIQUE,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		email VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE timesheet (
	
);